apiVersion: v1
kind: Service
metadata:
  name: autenticacion-frontend-ap
  namespace: autenticacion-ap
spec:
#   type: NodePort
  selector:
    app: autenticacion-frontend-ap
  ports:
    - protocol: TCP
      port: 80
#       NodePort: 30001
      targetPort: 80